dist: bionic

language: bash # same as minimal
cache:
  directories:
    - $HOME/build/$TRAVIS_REPO_SLUG/../ccache
    - $HOME/build/$TRAVIS_REPO_SLUG/../download

install: 
  - bin/system-setup

addons:
  apt:
    packages:
      - cloud-utils
      - qemu-system
      - openbios-ppc

jobs:
  fast_finish: true # fail once any job fail

env:
  - ARCHES=aarch64
  - ARCHES=arm
  - ARCHES=i386
  - ARCHES=x86_64
  - ARCHES=powerpc
  - ARCHES=ppc64
  - ARCHES=ppc64le

script:
  # we want to test does image boots after build
  - "BOOTTEST=true QUIET=1 bin/build-release ${TRAVIS_TAG:-daily}"

deploy:
  provider: releases
  api_key:
    secure: lDNfsHVkj+b9/Q4b71t/VHVvjRA2zPZX/1EKibvv/rrlgqwcplUO81RteV7ibA2u0GY0XzHNb9YnKdb9AxAbnzOzrymo6WQu2TQe6OetlTmFO1tD49nkoS42cqornUTQXpB62HL8sOmCBzUTUyvLv4tKxaEPJbaSuEib31ktlpJBp06/GOTp2HwOyY0YoNtKAn28IJVAr0tQWb6E1v/OFPQMNd6K9jWsXEHiolyPcr+PW4tlmMfMEydZ9GvYg4uxhgIn4JHpEIAlu+b1Qsr6TV5cNyykZUOz97893bOFpmYA3fEVpzgowzsu2exFEiTPSv8ls89GGmplCTxfvKLDwKp02Zt5VGR7+m/0ajFLs/9pZ9t47Kpz40BuJ+s40Mr2JNE8tNbmADmUq4FNT2xR6kEz8HFRGqKEvnEbgBe3X51dC20NQ3/kUbUISo1qH58rDr+RVaSOJvGXDhkMEUPWwEJCSE3k/LJPTaBWPQyDMVGhFU0/7jYI4o5bW/yuMjKQz0/bz6elUBdbmviv5gYNSeYz6+YqatcfgoWJAOFuXTsxLh9W7JZ9mlwQ2lOuWmevNyHEB6Ry5oEpBbhgZpYcqi03BCmEUhKgIC83XVGuMRicVb2kkIY2sWuPJWpR1ViSt3p2slb95YbOKHo6LqROv7Dp+Lm1h7WalhvhK3qLpn0=
  file: "$HOME/build/$TRAVIS_REPO_SLUG/../build-*/release/cirros-*"
  file_glob: true
  skip_cleanup: true  # we want build artifacts
  on:
    tags: true
    repo: cirros-dev/cirros
