dist: bionic

language: bash # same as minimal
cache:
  directories:
    - $HOME/build/$TRAVIS_REPO_SLUG/../ccache
    - $HOME/build/$TRAVIS_REPO_SLUG/../download

install: 
  - bin/system-setup

addons:
  apt:
    packages:
      - cloud-utils
      - qemu-system
      - openbios-ppc

jobs:
  fast_finish: true # fail once any job fail

env:
  - ARCHES=aarch64
  - ARCHES=arm
  - ARCHES=i386
  - ARCHES=x86_64
  - ARCHES=powerpc
  - ARCHES=ppc64
  - ARCHES=ppc64le

script:
  # we want to test does image boots after build
  - BOOTTEST=true QUIET=1 bin/build-release daily
